---
image:
  repository: ghcr.io/aacebedo/hugo-deployer
  tag: 2.14.5
  pullPolicy: Always

ingress:
  annotations: {}
  labels: {}
  host: ""
  path: /
  tls:
    enabled: false

nodeSelector: {}
resources:
  limits:
    cpu: 1500m
    memory: 2400Mi
  requests:
    cpu: 75m
    memory: 200Mi

dnsConfig:
  dnsPolicy: ""
  nameservers: []
  searches: []
  options: []

siteConfig:
  updateAPIKey: ""
  gitRepoURL: ""
  gitBranch: ""
  gitUsername: ""
  gitToken: ""
  pathPrefix: ""
