# The answers the Boilerplate templates were applied with, and the template
# version they were rendered from. Rewritten by "mise run update-templates".
---
template_url: https://github.com/aacebedo/boilerplate-templates.git
template_ref: v0.5.0
devcontainer: true
github_owner: aacebedo
layers: container,helmcharts
license: MIT
project_description: Docker image deploying a Hugo website, with automatic updates when a specific endpoint is called
project_name: hugo-deployer
project_slug: hugo-deployer
