dictionaries = ["en_us"]

words = [
  "aacebedo",
  "abiosoft",
  "acebedo",
  "actionid",
  "adrienverge",
  "addgroup",
  "adduser",
  "ajeetdsouza",
  "alexandre",
  "anchore",
  "apparmor",
  "appuser",
  "aquasecurity",
  "atuin",
  "atuinsh",
  "autodiscover",
  "autodiscovered",
  "autoload",
  "automount",
  "biomejs",
  "bindkey",
  "blopker",
  "bootsrap",
  "bridgecrewio",
  "bsdtar",
  "buildx",
  "caddy",
  "caddyfile",
  "caddyserver",
  "captureindex",
  "checkov",
  "chmod",
  "chown",
  "chrischinchilla",
  "ckv",
  "cjs",
  "cli",
  "cocogitto",
  "codeql",
  "commitizen",
  "commitmessage",
  "commitusingapi",
  "compdump",
  "compinit",
  "configmap",
  "cron",
  "cpython",
  "dasel",
  "dependson",
  "devcontaineruser",
  "disableconditions",
  "disktype",
  "dockerimage",
  "dprint",
  "editorconfig",
  "eof",
  "eux",
  "euxo",
  "exiasr",
  "eza",
  "filematch",
  "findsubmatch",
  "formulahendry",
  "fpath",
  "fzf",
  "gcompat",
  "gopath",
  "gohugoio",
  "githubrelease",
  "gpgsign",
  "groupby",
  "groupmod",
  "gruntwork",
  "gtrash",
  "hadolint",
  "healthcheck",
  "helmlint",
  "idursun",
  "initialise",
  "jbc",
  "jbm",
  "jdx",
  "jjk",
  "jjui",
  "johndoe",
  "jtyr",
  "jujutsu",
  "koalaman",
  "kubernetes",
  "kube",
  "kubeconform",
  "lazygit",
  "libcap",
  "libgcc",
  "libstdc",
  "linters",
  "liveness",
  "lla",
  "lzt",
  "matchpattern",
  "matthewpi",
  "mergify",
  "mise",
  "misconfig",
  "mkdir",
  "mvdan",
  "nameservers",
  "ndots",
  "neovim",
  "networkpolicy",
  "nginx",
  "nopasswd",
  "onbuild",
  "opencontainers",
  "passwordless",
  "pipefail",
  "pipx",
  "podman",
  "prek",
  "pullrequest",
  "pypi",
  "replacepattern",
  "rioj",
  "ripgrep",
  "rumdl",
  "rtk",
  "rvben",
  "sarif",
  "scmid",
  "scms",
  "sed",
  "setcap",
  "sharkdp",
  "shellcheck",
  "shfmt",
  "signingkey",
  "siteconfig",
  "sourceid",
  "stackrox",
  "starship",
  "subgid",
  "subid",
  "subuid",
  "tagfilter",
  "tberman",
  "timonwong",
  "tls",
  "tombi",
  "trimprefix",
  "trivy",
  "umask",
  "umlx",
  "updatecli",
  "usermod",
  "versionfilter",
  "virtualenv",
  "vscode",
  "wget",
  "xcaddy",
  "xzf",
  "yamllint",
  "yannh",
  "zoxide",
  "zstyle",
]

ignore_paths = [
  "CHANGELOG.md",
  ".vale/**",
  ".git/**",
  ".jj/**",
  "trivy.yaml",
  "charts/hugo-deployer/tests/secrets_test.yaml",
]
