dictionaries = ["en_us"]

words = [
  "aacebedo",
  "actionid",
  "aquasecurity",
  "autodiscover",
  "autodiscovered",
  "autodiscovery",
  "autoqueue",
  "biomejs",
  "blopker",
  "captureindex",
  "cjs",
  "cli",
  "cocogitto",
  "codebook",
  "commitizen",
  "commitmessage",
  "commitusingapi",
  "boilerplate",
  "cron",
  "devcontainer",
  "devcontaineruser",
  "dprint",
  "dotfiles",
  "editorconfig",
  "findsubmatch",
  "fmt",
  "githubrelease",
  "gohugoio",
  "groupby",
  "gruntwork",
  "hidecredit",
  "jdx",
  "koalaman",
  "linters",
  "matchpattern",
  "mergify",
  "mikefarah",
  "misconfig",
  "mise",
  "mise's",
  "mkdir",
  "mvdan",
  "owenlamont",
  "pep440",
  "pipefail",
  "pipx",
  "prek",
  "pullrequest",
  "pypi",
  "replacepattern",
  "rumdl",
  "rvben",
  "ryl",
  "scmid",
  "scms",
  "scop",
  "sed",
  "shellcheck",
  "shfmt",
  "sourceid",
  "tombi",
  "trimprefix",
  "trivy",
  "updatecli",
  "venv",
  "versionfilter",
  "wasm",
  "yamllint",
  "yamllint's",
  "apparmor",
  "cgroupns",
  "dockerfile",
  "dockerimage",
  "hadolint",
  "nofile",
  "opencontainers",
  "podman",
  "reteps",
  "tagfilter",
  "trivyignore",
  "ulimit",
  "fullname",
  "helmcharts",
  "unittest",
  "abiosoft",
  "addgroup",
  "adduser",
  "appuser",
  "automount",
  "backgrounded",
  "bsdtar",
  "caddy",
  "caddyfile",
  "caddyserver",
  "checkov",
  "chmod",
  "chown",
  "ckv",
  "configmap",
  "disktype",
  "eof",
  "euxo",
  "exec'd",
  "gcompat",
  "gopath",
  "healthcheck",
  "johndoe",
  "kubernetes",
  "libgcc",
  "libstdc",
  "liveness",
  "ndots",
  "nameservers",
  "networkpolicy",
  "nginx",
  "siteconfig",
  "subgid",
  "subid",
  "subuid",
  "tls",
  "wget",
  "xcaddy",
  "xzf",
]

ignore_paths = [
  ".boilerplate-answers.yaml",
  "CHANGELOG.md",
  "cog.toml",
  ".git/**",
  "REUSE.toml",
  "charts/hugo-deployer/tests/secrets_test.yaml",
  "trivy.yaml",
]
