---
ignored:
  # Pinning versions in `apk add` is left to the base image.
  - DL3018
  # Consecutive RUN instructions are allowed.
  - DL3059
  # podman ignores the SHELL instruction for the Docker image format, so the "set SHELL -o pipefail" advice from
  # hadolint can't be followed there.
  - DL4006
