---
queue_rules:
  - merge_method: fast-forward
    name: default
    autoqueue: true
    autosquash: true
    branch_protection_injection_mode: merge
    merge_conditions:
      - and:
          - label = reviewed
          - check-success = cleanup / cleanup-devcontainer-image
          - check-success = build
          - check-success = prepare / prepare-devcontainer-image
          - check-success = lint
merge_protections:
  - name: Accept push from semantic-release bot
    description: Accept pushes from the semantic-release bot
    if:
      - base = main
    success_conditions:
      - or:
          - author = semantic-release-bot
          - author = renoate[bot]
