pull_request_rules:
  - name: merge any approved PR
    conditions:
      - "#approved-reviews-by=@aacebedo >= 1"
      - "status-success=pr"
      - "base=main"
    actions:
      update:
        strict: true
      merge:
        method: rebase
