---
queue_rules:
  - merge_method: merge
    name: default
    autoqueue: true
    branch_protection_injection_mode: merge
    merge_conditions:
      - and:
          - label = reviewed
          - check-success = cleanup / cleanup-devcontainer-image
          - check-success = pr-checks
          - check-success = prepare / prepare-devcontainer-image
merge_protections:
  - name: Merge only if reviewed
    description: Merge only if the PR has been reviewed
    if:
      - base = main
    success_conditions:
      - label = reviewed
