queue_rules:
  - merge_method: rebase
    name: default
    autoqueue: true
    autosquash: true
    branch_protection_injection_mode: merge
    merge_conditions:
      - and:
          - check-success = cleanup
          - check-success = build
          - check-success = prepare
          - check-success = lint
