---
version: '3.8'

services:
  hugo-site:
    build:
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_TOKEN=${GIT_TOKEN}
      - GIT_BRANCH=${GIT_BRANCH}
      - UPDATE_API_KEY=${UPDATE_API_KEY}
    volumes:
      - ${HOOKS_DIR}:/app/config/hooks
    restart: unless-stopped
