[settings]
experimental = true

[[env]]
CGO_ENABLED = 1
HELM_PLUGINS = { value = "{{ tools['http:helm-kubeconform'].path | default(value=\"\") }}", tools = true }

[tools]
uv = "0.11.1"
shellcheck = "0.11.0"
go = "1.26.4"
"pipx:podman-compose" = "1.6.0"
kube-linter = "0.8.1"
kubeconform = "0.8.0"
helm = "4.2.0"
"pipx:checkov" = "3.3.5"
editorconfig-checker = "3.8.0"
hadolint = "2.14.0"
taplo = "0.10.0"
prek = "0.4.1"
trivy = "0.72.0"
vale = "3.15.1"
yamllint = "1.38.0"
node = "24.18.0"
python = "3.14.2"
"github:cocogitto/cocogitto" = "7.0.0"
gh = "2.97.0"
dprint = "0.55.2"

[tools."npm:renovate"]
version = "44.7.0"
trust_policy_excludes = ["@yarnpkg/libzip"]

[tools."http:helm-kubeconform"]
version = "0.2.0"
url = "https://github.com/jtyr/kubeconform-helm/archive/refs/tags/v{{version}}.tar.gz"
depends = ["helm", "kubeconform"]

[vars]
# editorconfig-checker-disable
repo_owner = '''{{ exec(command="git remote get-url origin 2>/dev/null | sed 's/[.]git$//' | awk -F'[/:]' '{print $(NF-1)}' || echo ''") | trim }}'''
repo_name = '''{{ exec(command="git remote get-url origin 2>/dev/null | sed 's/[.]git$//' | awk -F'[/:]' '{print $NF}' || echo ''") | trim }}'''
# editorconfig-checker-enabne
repo_url = "https://github.com/{{vars.repo_owner}}/{{vars.repo_name}}"
image_name = "ghcr.io/{{vars.repo_owner}}/{{vars.repo_name}}"
commit_sha = '''{{ exec(command="git rev-parse HEAD 2>/dev/null || echo ''") | trim }}'''

[bootstrap.packages]
"apt:bash" = "latest"
"apt:podman" = "latest"
"apt:podman-docker" = "latest"
"apt:fuse-overlayfs" = "latest"
"apt:iptables" = "latest"
"apt:build-essential" = "latest"
"apt:curl" = "latest"
"apt:git" = "latest"
