[settings]
experimental = true

[tools]
"pipx:podman-compose" = "1.6.0"

[bootstrap.packages]
"apt:bash" = "latest"
"apt:podman" = "latest"
"apt:passt" = "latest"
"apt:fuse-overlayfs" = "latest"
"apt:iptables" = "latest"
"apt:nftables" = "latest"
"apt:aardvark-dns" = "latest"
"apt:build-essential" = "latest"
"apt:curl" = "latest"
"apt:git" = "latest"
"apt:uidmap" = "latest"
