---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-siteconfig'
data:
  GIT_REPO_URL: "{{ .Values.siteConfig.gitRepoURL }}"
  GIT_BRANCH: {{ .Values.siteConfig.gitBranch | quote }}
  {{- if .Values.siteConfig.pathPrefix }}
  PATH_PREFIX: {{ .Values.siteConfig.pathPrefix | quote }}
  {{- end }}
  {{- if .Values.env }}
{{- toYaml .Values.env | nindent 2 }}
  {{- end }}
