[tools]
shellcheck = "0.11.0"
"github:editorconfig-checker/editorconfig-checker" = "4.0.2"
trivy = "0.74.0"
"github:owenlamont/ryl" = "0.22.0"
prek = "0.5.3"
shfmt = "3.14.1"
dprint = "0.57.4"
"github:tombi-toml/tombi" = "1.5.5"
"github:cocogitto/cocogitto" = "7.0.0"
gh = "2.101.0"
rumdl = "0.2.76"
updatecli = "0.121.0"
biome = "2.5.14"
"github:blopker/codebook" = "0.3.43"
uv = "0.12.18"
"pipx:reuse" = { version = "6.2.0", extras = "charset-normalizer" }
boilerplate = "0.16.0"
yq = "4.53.6"

[vars]
# editorconfig-checker-disable
repo_host = '''{{ exec(command="git remote get-url origin 2>/dev/null |
  sed 's/[.]git$//' |
  awk -F'[/:]' '{print $(NF-2)}' |
  sed 's/.*@//' || echo ''") | trim }}'''
repo_owner = '''{{ exec(command="git remote get-url origin 2>/dev/null |
  sed 's/[.]git$//' |
  awk -F'[/:]' '{print $(NF-1)}' || echo ''") | trim }}'''
repo_name = '''{{ exec(command="git remote get-url origin 2>/dev/null |
  sed 's/[.]git$//' |
  awk -F'[/:]' '{print $NF}' || echo ''") | trim }}'''
# editorconfig-checker-enable
repo_url = "https://{{vars.repo_host}}/{{vars.repo_owner}}/{{vars.repo_name}}"
commit_sha = '''{{ exec(command="git rev-parse HEAD 2>/dev/null || echo ''") | trim }}'''

[task_config]
includes = [
  "git::https://github.com/aacebedo/boilerplate-templates.git//static_files/mise/tasks/base?ref=v0.3.3",
  "git::https://github.com/aacebedo/boilerplate-templates.git//static_files/mise/tasks/container?ref=v0.3.3",
  "git::https://github.com/aacebedo/boilerplate-templates.git//static_files/mise/tasks/helmcharts?ref=v0.3.3",
  ".mise/tasks",
]
