{{- range $i, $dep := .prekHooks }}
{{- if $i }}
---
{{- end }}
name: "Bump {{ $dep.slug }} rev in prek.toml"

scms:
  default:
    kind: github
    spec:
      owner: '{{ $.github.owner }}'
      repository: '{{ $.github.repository }}'
      branch: '{{ $.github.branch }}'
      user: '{{ $.github.user }}'
      email: '{{ $.github.email }}'
      token: '{{ requiredEnv $.github.token }}'
      commitmessage:
        type: fix
        scope: deps

actions:
  default:
    kind: github/pullrequest
    scmid: default
    spec:
      title: 'fix(deps): bump {{ $dep.slug }} to {{ "{{" }} source "{{ $dep.slug }}" {{ "}}" }}'

sources:
  {{ $dep.slug }}:
    name: "Get the latest {{ $dep.owner }}/{{ $dep.repo }} release"
    kind: githubrelease
    spec:
      owner: {{ $dep.owner }}
      repository: {{ $dep.repo }}
      token: '{{ requiredEnv $.github.token }}'
  {{- if $dep.comment }}
      # {{ $dep.comment }}
  {{- end }}
      versionfilter:
  {{- if $dep.versionfilterKind }}
        kind: {{ $dep.versionfilterKind }}
        pattern: '{{ $dep.versionfilterPattern }}'
  {{- else }}
        kind: semver
        pattern: '*'
  {{- end }}

targets:
  {{ $dep.slug }}:
    name: "Bump {{ $dep.slug }} rev in prek.toml"
    kind: file
    scmid: default
    sourceid: {{ $dep.slug }}
    spec:
      file: prek.toml
      matchpattern: '(repo = "{{ $dep.repoUrlPattern }}"\nrev = )"[^"]+"'
      replacepattern: '${1}"{{ "{{" }} source "{{ $dep.slug }}" {{ "}}" }}"'
{{- end }}
