---
name: PR

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prepare:
    uses: ./.github/workflows/prepare-devcontainer-image.yaml
    permissions:
      contents: read
      packages: write
  lint:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Run pre-commit to lint
        run: |
          just lint
  build:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root --privileged
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Build
        run: |
          just build
      - name: Run securiy scan
        id: security-scan
        run: |
          just security-scan
          echo "sarif=/tmp/trivy-results.sarif" >> $GITHUB_OUTPUT
      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.security-scan.outputs.sarif }}

  cleanup:
    uses: ./.github/workflows/cleanup-devcontainer-image.yaml
    needs:
      - prepare
      - lint
      - build
    if: always()
    permissions:
      packages: write
