---
name: Prepare devcontainer image

# yamllint disable-line rule:truthy
on:
  workflow_call:

jobs:
  prepare-devcontainer-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push devcontainer image
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer
          push: true
          tags: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: image
          scan-ref: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
