---
name: Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    runs-on: ubuntu-26.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    permissions:
      contents: write
      packages: write
      actions: read
      security-events: write
    container:
      image: ghcr.io/aacebedo/devcontainer-base:1.21.1
      options: --user root --privileged --cgroupns=host --security-opt apparmor=unconfined --device /dev/fuse
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ secrets.CI_ACTIONS_RELEASER_CLIENT_ID }}
          private-key: ${{ secrets.CI_ACTIONS_RELEASER_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ steps.generate-token.outputs.token }}
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
      - name: Perform release
        id: release
        run: |
          mise release
          echo "sarif=/tmp/trivy-results.sarif" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v4.37.9
        with:
          sarif_file: ${{ steps.release.outputs.sarif }}
