---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: aacebedo/boilerplate-templates/.github/workflows/reusable-release.yaml@v0.3.3
    secrets: inherit
    permissions:
      contents: write
      packages: write

    with:
      container-image: ghcr.io/aacebedo/devcontainer-base:1.24.1
      container-options: >-
        --user root
        --privileged --cgroupns=host --security-opt apparmor=unconfined --device /dev/fuse
