---
name: Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prepare:
    uses: ./.github/workflows/prepare-devcontainer-image.yaml
    permissions:
      contents: read
      packages: write
    secrets:
        PACKAGE_MANAGEMENT_TOKEN: ${{ secrets.PACKAGE_MANAGEMENT_TOKEN }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
  release:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      security-events: write
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root --privileged
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Perform test
        run: |
          just test
      - name: Run securiy scan
        id: security-scan
        run: |
          just security-scan
          echo "sarif=/tmp/trivy-results.sarif" >> $GITHUB_OUTPUT
      - name: Perform release
        run: |
          just release
      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.security-scan.outputs.sarif }}
  cleanup:
    uses: ./.github/workflows/cleanup-devcontainer-image.yaml
    if: always()
    secrets:
      PACKAGE_MANAGEMENT_TOKEN: ${{ secrets.PACKAGE_MANAGEMENT_TOKEN }}

