---
name: Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  prepare:
    uses: ./.github/workflows/prepare-devcontainer-image.yaml
    permissions:
      contents: read
      packages: write
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
  release:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      security-events: write
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root --privileged
    env:
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          token: ${{ steps.generate-token.outputs.token }}
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Perform release
        id: release
        run: |
          just release
          echo "sarif=/tmp/trivy-results.sarif" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.release.outputs.sarif }}
  cleanup:
    uses: ./.github/workflows/cleanup-devcontainer-image.yaml
    needs:
      - prepare
      - release
    permissions:
      packages: write
    if: always()
