---
name: Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: {}
jobs:
  prepare:
    uses: ./.github/workflows/prepare-devcontainer-image.yaml
    permissions:
      contents: read
      packages: write
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

  release:
    needs: prepare
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      packages: write
      actions: read
      security-events: write
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root --privileged
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ steps.generate-token.outputs.token }}
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
      - name: Perform release
        id: release
        run: |
          mise release
          echo "sarif=/tmp/trivy-results.sarif" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.release.outputs.sarif }}
  cleanup:
    uses: ./.github/workflows/cleanup-devcontainer-image.yaml
    needs:
      - prepare
      - release
    permissions:
      packages: write
    if: always()
