---
name: Update dependencies

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
permissions: {}
jobs:
  update-deps:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    container:
      image: ghcr.io/aacebedo/devcontainer-base:1.21.1
      options: --user root --privileged

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ secrets.CI_ACTIONS_DEP_UPDATER_CLIENT_ID }}
          private-key: ${{ secrets.CI_ACTIONS_DEP_UPDATER_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup
        uses: ./.github/actions/setup
      - name: Apply update policies
        run: mise run update-deps --apply
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
