---
name: Update dependencies

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

permissions: {}

jobs:
  update-deps:
    uses: aacebedo/boilerplate-templates/.github/workflows/reusable-update-deps.yaml@v0.3.2
    permissions:
      contents: read
    secrets: inherit
